### ISSUE TITLE
Drop support for `__dependency_links__`

### ISSUE THREAD

**Issue by jaraco** [jaraco/pip-run#41]
In #24, this project adopted support for specifying `--dependency-links` in a script to support VCS installation. Since then (or perhaps before), pip added support for VCS URLs directly in requirements. Let's remove this now deprecated functionality.

**Comment by jaraco** [comment]
I started looking into removing `__dependency_links__`, but as you can see in the commit above, even when adapting the test to the recommended syntax, it doesn't work because:

```
>>> list(pkg_resources.parse_requirements('file:///private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pytest-of-jaraco/pytest-28/test_pkg_loaded_from_url0/barbazquux-1.0#egg=barbazquux-1.0'))
Traceback (most recent call last):
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 90, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3205, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected stringEnd (at char 4), (line:1, col:5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 92, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Invalid requirement, parse error at "':///priv'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "/Users/jaraco/code/main/pip-run/.tox/python/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pkg_resources.RequirementParseError: Invalid requirement, parse error at "':///priv'"
```

The only reason it doesn't error is because pip-run is [lenient about reading requirements from a file](https://github.com/jaraco/pip-run/blob/c4938de84c9b6b91bbafd06c4f9941343108983c/pip_run/scripts.py#L46-L56).

**Comment by jaraco** [comment]
Instead of relying on `dependency_links`, `pip-run` should probably support a syntax that matches with what `pip install` expects.
